# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.synced_folder "../src/", "/var/jsondgc"
  config.vm.provider "virtualbox" do |v|
	  v.memory = 512
	  v.cpus = 1
  end
  config.vm.provision "shell" do |s|
   s.path = "deploy.sh"
   s.privileged = true
  end
end
